# port
server:
  port: 8081
  servlet:
    context-path: /sample

# datasource
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: true
    prefix: classpath:/templates/
    suffix: .html
    mode: html5
    servlet:
      content-type: text/html
    check-template-location: true
    check-template: true

#MyBatis
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.fangyx.exo

#showSql
logging:
  level:
    com:
      example:
        mapper : debug